/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_jpountz_lz4_LZ4JNI_LZ4FError */

#ifndef _Included_net_jpountz_lz4_LZ4JNI_LZ4FError
#define _Included_net_jpountz_lz4_LZ4JNI_LZ4FError
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
